# Generated by Django 2.2.3 on 2019-07-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteanswer',
            name='num',
            field=models.IntegerField(max_length=10),
        ),
    ]
