# Generated by Django 2.2.3 on 2019-07-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitmall', '0002_addgoods_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='addgoods',
            name='wight',
            field=models.IntegerField(default=100),
        ),
    ]
