# Generated by Django 2.2.3 on 2019-07-06 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookproject', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='country',
            new_name='ctry',
        ),
    ]
