# Generated by Django 2.2.3 on 2019-07-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookproject', '0002_auto_20190706_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='gender',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], max_length=10),
        ),
    ]
